name: Enviar correo al hacer push

on:
  push:
    branches:
      - main
      - feature_a
      - feature_b

jobs:
  enviar-correo:
    runs-on: ubuntu-latest
    steps:
    - name: Enviar correo
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Cambios subidos a rama ${{ github.ref_name }}
        body: Cambios realizados en la rama ${{ github.ref_name }}.
        to: ro.net.work.99@gmail.com
